### PR TITLE
Fixes markdown table syntax

### LINKED ISSUE #4: Markdown tables are misformatted
See discussion on this commit: https://github.com/ashfurrow/danger-rubocop/commit/dfad65820f277ffa12055a13ae73d11cdb204413#commitcomment-18463581

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #4. Added a test to make sure the output is formatted precisely. @segiddins @timriley thoughts? If there are no objects, I'll merge+push a new version.

### CODE REVIEW

**Comment by timriley** [comment]
This looks good to me! Thanks!

**Comment by timriley** [comment]
Actually, in testing this branch out, I'm seeing the updated table syntax when danger edits her PR comment, but it's still rendering as plain text, instead of markdown.

It looks like the problem is this. Danger generates this for the table header (n.b. the top line is a "bar"):

```md
|---------------------------------------|------|-------------------------------------------------------------------------------------------------------------------------------|
| File                                  | Line | Reason                                                                                                                        |
|---------------------------------------|------|-------------------------------------------------------------------------------------------------------------------------------|
```

But [Github expects this format](https://help.github.com/articles/organizing-information-with-tables/) for tables (i.e. no top "bar" at all):

```md
| File                                  | Line | Reason                                                                                                                        |
|---------------------------------------|------|-------------------------------------------------------------------------------------------------------------------------------|
```

If I go to edit Danger's comment manually and remove that top bar, then switch over to the preview tab, the table renders properly.

**Comment by ashfurrow** [comment]
Ah, thanks for checking! I'll take another look at the gem's configuration options.

**Comment by timriley** [comment]
Sadly, that top separator line does not look configurable: https://github.com/tj/terminal-table/blob/c16bd19130d77ad79886d9a4467ebf34d157b43f/lib/terminal-table/table.rb#L112

I'm testing out this fix now: https://github.com/timriley/danger-rubocop/commit/6dae93c17beaaf88295a80e8a06eefba174a981c

**Comment by ashfurrow** [comment]
Nice, just pushed this: https://github.com/ashfurrow/danger-rubocop/pull/5/commits/672496c2d0f1e95d72ebf48b7bb5cd24d9d83e0c

**Comment by timriley** [comment]
Nice, TIL `Array#drop`! 

I've confirmed that we now have proper table formatting via the CI build that ran on my fork.

There's one thing we'll need to do, still: remove the _last_ separator bar on the table as well, otherwise we get this:

screen shot 2016-08-01 at 9 47 24 am

**Comment by ashfurrow** [comment]
Coo! https://github.com/ashfurrow/danger-rubocop/pull/5/commits/49033a922e28c9136a3f53fe1ba24d13f00ee962 should do it.

**Comment by timriley** [comment]
Thanks! And thanks for bearing with this iterative process :)

**Comment by ashfurrow** [comment]
No problem at all! It's been great!

**Pull request merged**
